version: '3.8'
services:

  database:
    image: "mongo:latest"
    container_name: mongo_database
    volumes:
      - mongo_db:/data/db
    ports:
      - 2717:27017
    restart: always


  backend:
    build: ./backend
    container_name: backend
    ports:
      - 5000:5000
    # links:
    #   - mongo_database
    environment:
      MONGODB_URL: "mongodb://mongo_database:27017"
    depends_on:
      - database
    volumes:
      - ./backend:/app


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    links:
      - backend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app


volumes:
  mongo_db:
    name: 'jtpproj_mongo_db'